export const userType = {
  GETALL_REQUEST: "GETALL_REQUEST",
  GETALL_SUCCESS: "GETALL_SUCCESS",
  GETALL_ERROR: "GETALL_ERROR",

  GETBYID_REQUEST: "GETBYID_REQUEST",
  GETBYID_SUCCESS: "GETBYID_SUCCESS",
  GETBYID_ERROR: "GETBYID_ERROR",
};

export const itemType = {
  GETALL_REQUEST: "GETALL_ITEM_REQUEST",
  GETALL_SUCCESS: "GETALL_ITEM_SUCCESS",
  GETALL_ERROR: "GETALL_ITEM_ERROR",

  GETBYID_REQUEST: "GETBYID_REQUEST",
  GETBYID_SUCCESS: "GETBYID_SUCCESS",
  GETBYID_ERROR: "GETBYID_ERROR",

  ADD_REQUEST: "ADD_ITEM_REQUEST",
  ADD_SUCCESS: "ADD_ITEM_SUCCESS",
  ADD_ERROR: "ADD_ITEM_ERROR",

  DELETE_REQUEST: "DELETE_ITEM_REQUEST",
  DELETE_SUCCESS: "DELETE_ITEM_SUCCESS",
  DELETE_ERROR: "DELETE_ITEM_ERROR",
};
